<?php

if (!class_exists('Redux')) {
    return;
}

// This is your option name where all the Redux data is stored.
$opt_name = "mstore_settings";

$theme = wp_get_theme(); // For use with some settings. Not necessary.
$args  = array(
    'opt_name'              => 'mstore_settings',
    'use_cdn'               => true,
    'display_name'          => 'Mobile Settings',
    'page_title'            => 'Setting Options',
    'update_notice'         => true,
    'admin_bar'             => true,
    'menu_type'             => 'menu',
    'menu_title'            => 'Mobile Settings',
    'allow_sub_menu'        => true,
    'page_parent_post_type' => 'mstoreapp',
    'customizer'            => true,
    'default_mark'          => '*',
    'hints'                 => array(
        'icon_position' => 'right',
        'icon_size'     => 'normal',
        'tip_style'     => array(
            'color' => 'light',
        ),
        'tip_position'  => array(
            'my' => 'top left',
            'at' => 'bottom right',
        ),
        'tip_effect'    => array(
            'show' => array(
                'duration' => '500',
                'event'    => 'mouseover',
            ),
            'hide' => array(
                'duration' => '500',
                'event'    => 'mouseleave unfocus',
            ),
        ),
    ),
    'output'                => true,
    'output_tag'            => true,
    'settings_api'          => true,
    'cdn_check_time'        => '1440',
    'compiler'              => true,
    'page_permissions'      => 'manage_options',
    'save_defaults'         => true,
    'show_import_export'    => true,
    'database'              => 'options',
    'transient_time'        => '3600',
    'network_sites'         => true,
);

// SOCIAL ICONS -> Setup custom links in the footer for quick links in your panel footer icons.

$args['share_icons'][] = array(
    'url'   => 'https://www.facebook.com',
    'title' => 'Like us on Facebook',
    'icon'  => 'el el-facebook',
);
$args['share_icons'][] = array(
    'url'   => 'http://twitter.com',
    'title' => 'Follow us on Twitter',
    'icon'  => 'el el-twitter',
);
$args['share_icons'][] = array(
    'url'   => 'http://www.linkedin.com',
    'title' => 'Find us on LinkedIn',
    'icon'  => 'el el-linkedin',
);

Redux::setArgs($opt_name, $args);

/*
 * ---> END ARGUMENTS
 */

/*
 * ---> START HELP TABS
 */

$tabs = array(
    array(
        'id'      => 'redux-help-tab-1',
        'title'   => __('Theme Information 1', 'admin_folder'),
        'content' => __('<p>This is the tab content, HTML is allowed.</p>', 'admin_folder'),
    ),
    array(
        'id'      => 'redux-help-tab-2',
        'title'   => __('Theme Information 2', 'admin_folder'),
        'content' => __('<p>This is the tab content, HTML is allowed.</p>', 'admin_folder'),
    ),
);
Redux::setHelpTab($opt_name, $tabs);

// Set the help sidebar
$content = __('<p>This is the sidebar content, HTML is allowed.</p>', 'admin_folder');
Redux::setHelpSidebar($opt_name, $content);

/*
 * <--- END HELP TABS
 */

/*
 *
 * ---> START SECTIONS
 *
 */

Redux::setSection($opt_name, array(
    'title' => __('Setting option', 'mstoreapp-settings'),
    'id'    => 'setting',
    'desc'  => __('', 'mstoreapp-settings'),
));

Redux::setSection($opt_name, array(
    'title'      => __('App Settings', 'mstoreapp-settings'),
    'desc'       => __('', 'mstoreapp-settings') . '',
    'id'         => 'lice_key',
    'subsection' => true,
    'fields'     => array(

        array(
            'id'          => 'app_name',
            'type'        => 'text',
            'title'       => __('APP Name', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('Enter mobile app name', 'mstoreapp-settings'),
            'placeholder' => 'APP Name',
        ),

        array(
            'id'          => 'site_url',
            'type'        => 'text',
            'title'       => __('Site URL', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('Enter site url like http://example.com', 'mstoreapp-settings'),
            'validate'    => 'url',
            'default'     => site_url(),
            'placeholder' => 'Site URL',
        ),

        array(
            'id'          => 'consumer_key',
            'type'        => 'text',
            'title'       => __('Consumer Key', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('Enter WooCommerce Consumer Key', 'mstoreapp-settings'),
            'placeholder' => 'Consumer Key',
        ),

        array(
            'id'          => 'consumer_secret',
            'type'        => 'text',
            'title'       => __('Consumer Secret', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('Enter WooCommerce Consumer Secret', 'mstoreapp-settings'),
            'placeholder' => 'Consumer Secret',
        ),

        array(
            'id'          => 'key',
            'type'        => 'text',
            'title'       => __('APP CODE', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('Enter purchase code or APP CODE', 'mstoreapp-settings'),
            'placeholder' => 'Purchase code',
        ),

    ),
));

Redux::setSection($opt_name, array(
    'title'      => __('Basic Setting', 'mstoreapp-settings'),
    'desc'       => __(' ', 'mstoreapp-settings') . '',
    'id'         => 'settings',
    'icon'       => '',
    'subsection' => true,
    'fields'     => array(
        array(
            'id'          => 'rate_app_url',
            'type'        => 'text',
            'title'       => __('Rate App URL', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'Rate App URL',
        ),

        array(
            'id'          => 'share_app_url',
            'type'        => 'text',
            'title'       => __('Share App URL', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'Share App URL',
        ),
        array(
            'id'          => 'onesignal_app_id',
            'type'        => 'text',
            'title'       => __('One Signal App Id', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'One Signal App Id',
        ),
        array(
            'id'          => 'google_pro_id',
            'type'        => 'text',
            'title'       => __('Google Project Id', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'Google Project Id',
        ),

        array(
            'id'          => 'web_client_id',
            'type'        => 'text',
            'title'       => __('Web Client Id', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'Web Client Id',
        ),
        array(
            'id'          => 'language',
            'type'        => 'text',
            'title'       => __('Language', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'Language',
        ),

        array(
            'id'       => 'app_dir',
            'type'     => 'radio',
            'mode'     => 'radio', // radio or text
            'title'    => __('App Direction', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('Select App Direction', 'mstoreapp-settings'),
            'options'  => array('RTL' => 'RTL', 'LTR' => 'LTR'),
            'default'  => 'RTL',

        ),

        array(
            'id'          => 'app_rate_win_id',
            'type'        => 'text',
            'title'       => __('App Rate Windows Id', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'App Rate Windows Id',
        ),

        array(
            'id'          => 'shareapp_msg',
            'type'        => 'text',
            'title'       => __('Share App Message', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'Share App Message',
        ),

        array(
            'id'          => 'shareapp_sub',
            'type'        => 'text',
            'title'       => __('Share App Subject', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'Share App Subject',
        ),

        array(
            'id'          => 'google_sharing',
            'type'        => 'text',
            'title'       => __('Google Sharing', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'Google Sharing',
        ),
        array(
            'id'          => 'ios_appurl',
            'type'        => 'text',
            'title'       => __('IOS App url', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'IOS App url',
        ),
        array(
            'id'          => 'support_mail',
            'type'        => 'text',
            'title'       => __('Support Mail', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'Support Mail',
        ),

        array(
            'id'          => 'shareapp_chooser_title',
            'type'        => 'text',
            'title'       => __('Share App Chooser Title', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'Share App Chooser Title',
        ),

        array(
            'id'          => 'web_link',
            'type'        => 'text',
            'title'       => __('Web Link', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'Web Link',
        ),

        array(
            'id'          => 'phone-no',
            'type'        => 'text',
            'title'       => __('Phone', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('', 'mstoreapp-settings'),
            'placeholder' => 'Phone Number',
        ),

        array(
            'id'       => 'show_rate_app',
            'type'     => 'switch',
            'title'    => __( 'Show Rate App', 'mstoreapp-settings' ),
            'subtitle' => __( '', 'mstoreapp-settings' ),
            'default'  => true,
        ),

        array(
            'id'       => 'show_share_app',
            'type'     => 'switch',
            'title'    => __( 'Show Share App', 'mstoreapp-settings' ),
            'subtitle' => __( '', 'mstoreapp-settings' ),
            'default'  => true,
        ),

        array(
            'id'       => 'show_contact_us',
            'type'     => 'switch',
            'title'    => __( 'Show Contact Us', 'mstoreapp-settings' ),
            'subtitle' => __( '', 'mstoreapp-settings' ),
            'default'  => true,
        ),

        array(
            'id'          => 'fb_url',
            'type'        => 'text',
            'title'       => __('Facebook URL', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('enter Facebook social link URL', 'mstoreapp-settings'),
            'placeholder' => 'Facebook URL',
        ),

        array(
            'id'          => 'twitter_url',
            'type'        => 'text',
            'title'       => __('Twitter URL', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('enetr Twitter social link URL', 'mstoreapp-settings'),
            'placeholder' => 'Twitter URL',
        ),

        array(
            'id'          => 'gp_url',
            'type'        => 'text',
            'title'       => __('Google Plus URL', 'mstoreapp-settings'),
            'subtitle'    => __('', 'mstoreapp-settings'),
            'desc'        => __('enter Google Plus social link URL', 'mstoreapp-settings'),
            'placeholder' => 'Google Plus URL',
        ),

        array(
            'id'       => 'home_recent_product',
            'type'     => 'switch',
            'title'    => __( 'Show recent product on home', 'mstoreapp-settings' ),
            'subtitle' => __( '', 'mstoreapp-settings' ),
            'default'  => true,
        ),
    ),
));

Redux::setSection($opt_name, array(
    'title' => __('Theme', 'mstoreapp-settings'),
    'id'    => 'theme',
    'desc'  => __('', 'mstoreapp-settings'),
    'icon'  => 'el el-brush',
));

Redux::setSection($opt_name, array(
    'title'      => __('Color Selection', 'mstoreapp-settings'),
    'desc'       => __(' ', 'mstoreapp-settings'),
    'id'         => 'color',
    'icon'       => '',
    'subsection' => true,
    'fields'     => array(
        array(
            'id'       => 'link-color',
            'type'     => 'link_color',
            'title'    => __('Link Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'hover'    => true,
            'active'   => true,
            'visited'  => false,
            'default'  => array(
                'regular' => '#dd3333',
                'hover'   => '#dd3333',
                'active'  => '#8224e3',
            ),
        ),
        array(
            'id'       => 'button_color',
            'type'     => 'link_color',
            'title'    => __('Button Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'hover'    => true,
            'active'   => true,
            'visited'  => false,
            'default'  => array(
                'regular' => '#dd3333',
                'hover'   => '#dd3333',
                'active'  => '#8224e3',
            ),
        ),
        array(
            'id'       => 'toggle_button_color',
            'type'     => 'link_color',
            'title'    => __('Toggle Button Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'hover'    => true,
            'active'   => true,
            'default'  => array(
                'regular' => '#dd3333',
                'hover'   => '#dd3333',
                'active'  => '#8224e3',
            ),
        ),
        array(
            'id'       => 'addcart_color',
            'type'     => 'link_color',
            'title'    => __('Add To Cart Button Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'hover'    => true,
            'active'   => true,
            'default'  => array(
                'regular' => '#dd3333',
                'hover'   => '#dd3333',
                'active'  => '#8224e3',
            ),
        ),
        array(
            'id'       => 'buynow_color',
            'type'     => 'link_color',
            'title'    => __('Buy Now Button Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'hover'    => true,
            'active'   => true,
            'default'  => array(
                'regular' => '#dd3333',
                'hover'   => '#dd3333',
                'active'  => '#8224e3',
            ),
        ),
        array(
            'id'       => 'header_color',
            'type'     => 'color',
            'title'    => __('Header Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'default'  => '#dd3333',
        ),
        array(
            'id'       => 'header_text_color',
            'type'     => 'color',
            'title'    => __('Header Text Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'default'  => '#ffffff',
        ),
        array(
            'id'       => 'sub_header_color',
            'type'     => 'color',
            'title'    => __(' Sub-Header Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'default'  => '#f7f7f7',
        ),
        array(
            'id'       => 'sub_header_text_color',
            'type'     => 'color',
            'title'    => __('Sub-Header Text Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'default'  => '#000',
        ),
        array(
            'id'       => 'header_icon_color',
            'type'     => 'link_color',
            'title'    => __('Header Icon Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'hover'    => true,
            'active'   => true,
            'default'  => array(
                'regular' => '#fff',
                'hover'   => '#dd3333',
                'active'  => '#8224e3',
            ),
        ),
        array(
            'id'       => 'page_bg_color',
            'type'     => 'color',
            'title'    => __('Page Background Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'default'  => '#dd3333',

        ),
        array(
            'id'       => 'menu_header_color',
            'type'     => 'color',
            'title'    => __('Menu Header Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'default'  => '#dd3333',
        ),
        array(
            'id'       => 'menu_bg_color',
            'type'     => 'color',
            'title'    => __('Menu Background Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'default'  => '#111',
        ),
        array(
            'id'       => 'menu_txt_color',
            'type'     => 'link_color',
            'title'    => __('Menu Text Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'hover'    => true,
            'active'   => true,
            'default'  => array(
                'regular' => '#fff',
                'hover'   => '#fff',
                'active'  => '#8224e3',
            ),
        ),
        array(
            'id'       => 'menu_border_color',
            'type'     => 'link_color',
            'title'    => __('Menu Border Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'hover'    => true,
            'active'   => true,
            'default'  => array(
                'regular' => '#3a3a3a',
                'hover'   => '#3a3a3a',
                'active'  => '#3a3a3a',
            ),
        ),
        array(
            'id'       => 'menu_right_arrow_color',
            'type'     => 'link_color',
            'title'    => __('Menu Right Arrow Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'hover'    => true,
            'active'   => true,
            'default'  => array(
                'regular' => '#909090',
                'hover'   => '#909090',
                'active'  => '#8224e3',
            ),
        ),
        array(
            'id'       => 'rating_icon_color',
            'type'     => 'color',
            'title'    => __('Rating Icon Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'default'  => '#ff4a00',
        ),
        array(
            'id'       => 'tab_color',
            'type'     => 'color',
            'title'    => __('Tab Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'default'  => '#dd3333',
        ),
        array(
            'id'       => 'tab_icon_color',
            'type'     => 'link_color',
            'title'    => __('Tab Icon Color', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'regular'  => true,
            'hover'    => true,
            'active'   => true,
            'default'  => array(
                'regular' => '#dd3333',
                'hover'   => '#dd3333',
                'active'  => '#8224e3',
            ),
        ),
    ),
));

    Redux::setSection( $opt_name, array(
        'title'      => __( 'Translation', 'mstoreapp-settings' ),
        'id'         => 'translation',
        'desc'       => __( 'Translate to your local language', 'mstoreapp-settings' ),
        'fields'     => array(
            array(
                'id'       => 'translation',
                'type'     => 'text',
                'title'    => __( 'Transaltion', 'mstoreapp-settings' ),
                'subtitle' => __( 'Translate text to your language.', 'mstoreapp-settings' ),
                'label'    => true,
                'options'  => array(
                     'About Us' => 'About Us',
                     'Account Info' => 'Account Info',
                     'Account' => 'Account',
                     'Add a review' => 'Add a review',
                     'Add From My Wishlist' => 'Add From My Wishlist',
                     'Add some products' => 'Add some products',
                     'Add To Cart' => 'Add To Cart',
                     'ADD' => 'ADD',
                     'Address Book' => 'Address Book',
                     'Address' => 'Address',
                     'Address Line 2' => 'Address Line 2',
                     'All categories' => 'All categories',
                     'Amount' => 'Amount',
                     'An email with password reset link has been sent to your mail address' => 'An email with password reset link has been sent to your mail address',
                     'Applied' => 'Applied',
                     'Apply Coupon and Offers' => 'Apply Coupon and Offers',
                     'Apply' => 'Apply',
                     'Arabic' => 'Arabic',
                     'Back' => 'Back',
                     'Best'  => 'Best',
                     'Billing Address' => 'Billing Address',
                     'Browse categories' => 'Browse categories',
                     'Browse Our Menu' => 'Browse Our Menu',
                     'Buy now' => 'Buy now',
                     'By signing in you agree to our' => 'By signing in you agree to our',
                     'Cancel' => 'Cancel',
                     'Card Code' => 'Card Code',
                     'Card Number' => 'Card Number',
                     'Cart' => 'Cart',
                     'Categories'   => 'Categories',
                     'Categories' => 'Categories',
                     'Charges' => 'Charges',
                     'Check this product' => 'Check this product',
                     'Checkout' => 'Checkout',
                     'Chinese' => 'Chinese',
                     'Choose Payment Method' => 'Choose Payment Method',
                     'Choose Shipping' => 'Choose Shipping',
                     'City' => 'City',
                     'Clear' => 'Clear',
                     'Comment' => 'Comment',
                     'Company' => 'Company',
                     'Connect with Facebook' => 'Connect with Facebook',
                     'Contact No' => 'Contact No',
                     'Contact Us' => 'Contact Us',
                     'Contact' => 'Contact',
                     'Continue as Guest' => 'Continue as Guest',
                     'Continue Checkout' => 'Continue Checkout',
                     'Continue Shopping' => 'Continue Shopping',
                     'Continue' => 'Continue',
                     'Country' => 'Country',
                     'Coupons' => 'Coupons',
                     'Coupon Code' => 'Coupon Code',
                     'Create Account' => 'Create Account',
                     'Create account password' => 'Create account password',
                     'Default' => 'Default',
                     'Delete' => 'Delete',
                     'Delivery Date' => 'Delivery Date',
                     'Delivery Time' => 'Delivery Time',
                     'Description' => 'Description',
                     'Dont have an account' => 'Dont have an account',
                     'Done' => 'Done',
                     'Edit Address' => 'Edit Address',
                     'Edit' => 'Edit',
                     'Email Us' => ' Email Us',
                     'Email' => 'Email',
                     'Ends in' => 'Ends in',
                     'Enter Email Address' => 'Enter Email Address',
                     'Error' => 'Error',
                     'Expiry Month' => 'Expiry Month',
                     'Expiry Year' => 'Expiry Year',
                     'Explore All' => 'Explore All',
                     'Facebook' => 'Facebook',
                     'Featured'  => 'Featured',
                     'Fee' => 'Fee',
                     'Feedback' => 'Feedback',
                     'Feedbacks' => 'Feedbacks',
                     'Filter' => 'Filter',
                     'First Name'  => 'First Name',
                     'Flash Sale' => 'Flash Sale',
                     'Forgot Password' => 'Forgot Password',
                     'French' => 'French',
                     'Gift Card Promo' => 'Gift Card Promo',
                     'Go Explore' => 'Go Explore',
                     'Go Shopping' => 'Go Shopping',
                     'Google' => 'Google',
                     'Grand Total' => 'Grand Total',
                     'Have a coupon? Enter below' => 'Have a coupon? Enter below',
                     'Hello' => 'Hello',
                     'Here' => 'Here',
                     'Hindi' => 'Hindi',
                     'Home' => 'Home',
                     'Home' => 'Home',
                     'I Agree' => 'I Agree',
                     'I have read and accept the' => 'I have read and accept the',
                     'In Stock' => 'In Stock',
                     'Information' => 'Information',
                     'Invalid username/password' => 'Invalid username/password',
                     'Italian' => 'Italian',
                     'Item has been added to cart' => 'Item has been added to cart',
                     'Item has been added to wishlist' => 'Item has been added to wishlist',
                     'Korean' => 'Korean',
                     'Landmark' => 'Landmark',
                     'Last Name'  => 'Last Name',
                     'Last Name' => 'Last Name',
                     'Last Orders' => 'Last Orders',
                     'Latest Products' => 'Latest Products',
                     'Less' => 'Less',
                     'Loading more items..' => 'Loading more items..',
                     'Logging In' => 'Logging In',
                     'Login' => 'Login',
                     'Logout' => 'Logout',
                     'Menu'   => 'Menu',
                     'More' => 'More',
                     'My Account' => 'My Account',
                     'MY SHOP' => 'MY SHOP',
                     'My' => 'My',
                     'Name' => 'Name',
                     'New Collections' => 'New Collections',
                     'New User' => 'New User',
                     'Next' => 'Next',
                     'No products found!' => 'No products found!',
                     'Notes about your order, e.g special notes for delivery' => 'Notes about your order, e.g special notes for delivery',
                     'No Stock' => 'No Stock',
                     'OFF' => 'OFF',
                     'Offer' => 'Offer',
                     'Offers on' => 'Offers on',
                     'Offers'  => 'Offers',
                     'OK' => 'OK',
                     'On Sale' => 'On Sale',
                     'Options' => 'Options',
                     'Oops!' => 'Oops!',
                     'Or' => 'Or',
                     'Or login via e-mail' => 'Or login via e-mail',
                     'Order date' => 'Order date',
                     'Order Details' => 'Order Details',
		     'Order has been cancelled' => 'Order has been cancelled',
		     'Order has been placed successfully' => 'Order has been placed successfully',
                     'Order ID' => 'Order ID',
                     'Order Info' => 'Order Info',
                     'Order Note' => 'Order Note',
                     'Order Number' => 'Order Number',
                     'Order Received' => 'Order Received',
                     'Order Summary' => 'Order Summary',
                     'Orders' => 'Orders',
                     'Out Of Stock' => 'Out Of Stock',
                     'Overview' => 'Overview',
                     'Password' => 'Password',
                     'Payment Method' => 'Payment Method',
                     'Phone' => 'Phone',
                     'Place Order' => 'Place Order',
                     'Please login' => 'Please login',
                     'Please Enter' => 'Please Enter',
                     'Please Select Product Option...' => 'Please Select Product Option...',
                     'Please Wait' => 'Please Wait',
                     'Postcode' => 'Postcode',
                     'Price details' => 'Price details',
                     'Price Range' => 'Price Range',
                     'Price' => 'Price',
                     'Proceed to CC Avenue' => 'Proceed to CC Avenue',
                     'Proceed to PayPal' => 'Proceed to PayPal',
                     'Proceed to PayU Money' => 'Proceed to PayU Money',
                     'Product Details' => 'Product Details',
                     'Product Name' => 'Product Name',
                     'Product' => 'Product',
                     'Products'  => 'Products',
                     'Products' => 'Products',
                     'Profile' => 'Profile',
                     'Quantity' => 'Quantity',
                     'Rate App' => 'Rate App',
                     'Rating & Feedback' => 'Rating & Feedback',
                     'Ratings' => 'Ratings',
                     'Read less' => 'Read less',
                     'Read more' => 'Read more',
                     'Recommended' => 'Recommended',
                     'Register Account' => 'Register Account',
                     'Register' => 'Register',
		     'Registering' => 'Registering',
                     'Registration successfull..' => 'Registration successfull..',
                     'Related Products' => 'Related Products',
                     'Related' => 'Related',
                     'Remove' => 'Remove',
                     'Reorder' => ' Reorder',
                     'Reset Password' => 'Reset Password',
                     'Reset' => 'Reset',
                     'Resetting' => 'Resetting',
                     'Returning customer? Login here' => 'Returning customer? Login here',
                     'Reviews' => 'Reviews',
                     'Russian' => 'Russian',
                     'Same For Shipping' => 'Same For Shipping',
                     'Save for later' => 'Save for later',
                     'Save' => 'Save',
                     'Saving' => 'Saving',
                     'Search Results' => 'Search Results',
                     'Search' => 'Search',
                     'See All' => 'See All',
                     'Select a shipping method' => 'Select a shipping method',
                     'Select Language' => 'Select Language',
                     'Select Option' => 'Select Option',
                     'Send reset link' => 'Send reset link',
                     'Sending' => 'Sending',
                     'Share App' => 'Share App',
                     'Share' => 'Share',
                     'Ship to' => 'Ship to',
                     'Ship to different address' => 'Ship to different address',
                     'Shipping Address' => 'Shipping Address',
                     'Shipping Method' => 'Shipping Method',
                     'Shipping Total' => 'Shipping Total',
                     'Shipping' => 'Shipping',
                     'Shop by Category'  => 'Shop by Category',
                     'SHOP NAME' => 'SHOP NAME',
                     'Shop'  => 'Home',
                     'Short Description' => 'Short Description',
                     'Show more' => 'Show more',
                     'Show Reviews' => 'Show Reviews',
                     'Sign In'  => 'Sign In',
                     'Sign Out'   => 'Sign Out',
                     'Sign Up' => 'Sign Up',
                     'Sold' => 'Sold',
                     'Sort' => 'Sort',
                     'Spanish' => 'Spanish',
                     'Specifications' => 'Specifications',
                     'Spent' => 'Spent',
                     'State' => 'State',
                     'Status' => 'Status',
                     'Street Address' => 'Street Address',
                     'Stripe Card Details' => 'Stripe Card Details',
                     'Sub Categories' => 'Sub Categories',
                     'SubCategories' => 'Sub Categories',
                     'Submit' => 'Submit',
                     'Subtotal' => 'Subtotal',
                     'Subtotal Ex Tax' => 'Subtotal Ex Tax',
                     'Success' => 'Success',
                     'Successfully submitted your comment' => 'Successfully submitted your comment',
                     'Tax Total' => 'Tax Total',
                     'Tax' => 'Tax',
                     'Terms & Conditions' => 'Terms & Conditions',
                     'Terms' => 'Terms',
                     'Thank you. Your order has been received' => 'Thank you. Your order has been received',
                     'Thank you for your review! Your review is awaiting approval' => 'Thank you for your review! Your review is awaiting approval',
                     'The most fulfilling shopping experience' => 'The most fulfilling shopping experience',
                     'There are no orders' => 'There are no orders',
                     'Total quantity' => 'Total quantity',
                     'Total' => 'Total',
                     'Translate Add' => 'Translate Add',
                     'Translate Grand Total' => 'Translate Grand Total',
                     'Type in your registered email id' => 'Type in your registered email id',
                     'Username' => 'Username',
                     'Variation' => 'Variation',
                     'View All' => 'View All',
                     'View Details' => 'View Details',
                     'Welcome' => 'Welcome',
                     'What are you looking for' => 'What are you looking for',
                     'Wishlist' => 'Wishlist',
                     'You are just one step away from signing up' => 'You are just one step away from signing up',
                     'You have successfully logged in' => 'You have successfully logged in',
                     'You may also like' => 'You may also like',
                     'You must log in to see your orders' => 'You must log in to see your orders',
		     'You must login to add item to wishlist' => 'You must login to add item to wishlist',
                     'You Pay' => 'You Pay',
                     'You will recieve an email to reset password' => 'You will recieve an email to reset password',
                     'Your Cart Is Empty' => 'Your Cart Is Empty',
                     'Your Orders' => 'Your Orders',
                     'Your Rating' => 'Your Rating',
                     'Your Wishlist Is Empty' => 'Your Wishlist Is Empty',
                     'Your' => 'Your',            
                )
            ),
        )
    ) );

Redux::setSection($opt_name, array(
    'title'  => __('Contents', 'mstoreapp-settings'),
    'id'     => 'required',
    'icon'   => 'el el-book',
    'desc'   => 'Add Contents here',
    'fields' => array(
        array(
            'id'       => 'show_about_us',
            'type'     => 'switch',
            'title'    => 'About Us',
            'subtitle' => 'Enable/Disable Terms About Us',
            'default'  => false,
        ),
        array(
            'id'       => 'about_us_button',
            'type'     => 'button_set',
            'title'    => 'Post id or Content',
            'subtitle' => 'Select either post id or content',
            'options'  => array(
                'id'      => 'Post ID',
                'content' => 'Content',
            ),
            'required' => array('show_about_us', '=', true),
            'default'  => 'button-text',
        ),
        array(
            'id'       => 'about_us_id',
            'type'     => 'text',
            'title'    => 'Enter post id',
            'required' => array('about_us_button', '=', 'id'),
        ),
        array(
            'id'       => 'about_us_content',
            'type'     => 'editor',
            'title'    => 'Enter Content',
            'required' => array('about_us_button', '=', 'content'),
        ),

        array(
            'id'       => 'show_terms',
            'type'     => 'switch',
            'title'    => 'Terms and Conditions',
            'subtitle' => 'Enable/Disable Terms and Conditions',
            'default'  => false,
        ),
        array(
            'id'       => 'terms_button',
            'type'     => 'button_set',
            'title'    => 'Post id or Content',
            'subtitle' => 'Select either post id or content',
            'options'  => array(
                'id'      => 'Post ID',
                'content' => 'Content',
            ),
            'required' => array('show_terms', '=', true),
            'default'  => 'button-text',
        ),
        array(
            'id'       => 'terms_id',
            'type'     => 'text',
            'title'    => 'Enter post id',
            'required' => array('terms_button', '=', 'id'),
        ),
        array(
            'id'       => 'terms_content',
            'type'     => 'editor',
            'title'    => 'Enter Content',
            'required' => array('terms_button', '=', 'content'),
        ),

        array(
            'id'       => 'show_privacy',
            'type'     => 'switch',
            'title'    => 'Privacy and Policy',
            'subtitle' => 'Enable/Disable Privacy and Policy',
            'default'  => false,
        ),
        array(
            'id'       => 'privacy_button',
            'type'     => 'button_set',
            'title'    => 'Post id or Content',
            'subtitle' => 'Select either post id or content',
            'options'  => array(
                'id'      => 'Post ID',
                'content' => 'Content',
            ),
            'required' => array('show_privacy', '=', true),
            'default'  => 'button-text',
        ),
        array(
            'id'       => 'privacy_id',
            'type'     => 'text',
            'title'    => 'Enter post id',
            'required' => array('privacy_button', '=', 'id'),
        ),
        array(
            'id'       => 'privacy_content',
            'type'     => 'editor',
            'title'    => 'Enter Content',
            'required' => array('privacy_button', '=', 'content'),
        ),
    ),
));
Redux::setSection($opt_name, array(
    'title' => __('Media Upload', 'mstoreapp-settings'),
    'id'    => 'media',
    'desc'  => __('', 'mstoreapp-settings'),
    'icon'  => 'el el-picture',
));

Redux::setSection($opt_name, array(
    'title'      => __('Media Upload Option', 'mstoreapp-settings'),
    'id'         => 'media-media',
    'desc'       => __('') . '',
    'subsection' => true,
    'icon'       => '',
    'fields'     => array(
        array(
            'id'       => 'logo',
            'type'     => 'media',
            'title'    => __('Logo image', 'mstoreapp-settings'),
            'desc'     => __('', 'mstoreapp-settings'),
            'subtitle' => __('', 'mstoreapp-settings'),
        ),
    ),
));

/*
 * <--- END SECTIONS
 */
